# Generated by Django 2.1.7 on 2019-03-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_product_details_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'цвет не установлен'), ('#000000', 'черные'), ('#81858b', 'серый'), ('#ad7c51', 'коричневый'), ('#ffffff', 'белый'), ('#f4dfbc', 'бежевый'), ('#8ab162', 'зеленый'), ('#f53b3b', 'красный'), ('#f5a623', 'желтый'), ('#3653a5', 'синий'), ('#d9b06b', 'охра'), ('#5487ae', 'голубой')], default='', max_length=24, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_colors',
            field=models.BooleanField(default=False, help_text='Отметьте это пунк, если вы хотите добавлять товары разных цветов. Товары добавляются в разделе Варианты.', verbose_name='Использовать цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='details_description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
    ]
