# Generated by Django 2.1.7 on 2019-03-09 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20190307_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, help_text='Хиты продаж на главной странице выводятся согласно рейтингу.<br>Допустимые значения рейтинга от 0 до 5.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг товара'),
        ),
    ]
