# Generated by Django 2.1.7 on 2019-03-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20190309_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_sale_price',
            field=models.BooleanField(default=False, help_text="Отметьте это пунк, если вы хотите отображать этот товар в разделе 'SALE'.Отображаемая 'Цена без скидки' указывается в разделе 'Цена и наличие'.", verbose_name='Отображать цену со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'цвет не установлен'), ('#000000', 'черные'), ('#81858b', 'серый'), ('#ffffff', 'белый'), ('#f53b3b', 'красный'), ('#ff6500', 'оранжевый'), ('#f5a623', 'желтый'), ('#8ab162', 'зеленый'), ('#5487ae', 'голубой'), ('#3653a5', 'синий'), ('#f4dfbc', 'бежевый'), ('#d9b06b', 'охра'), ('#ad7c51', 'коричневый')], default='', max_length=24, verbose_name='Цвет'),
        ),
    ]
